### ISSUE TITLE
Add ability for users to print/modify the restaurant list

### ISSUE THREAD

**Issue by n-martin** [ChristopherzwTan/slack_memebot#7]
As a user, I would like to be able to add/remove restaurants to the list used to randomly choose a place to eat. Additionally, as a user, I would like to be able to print the list of restaurants from within Slack privately (so as not to both the other users).

**Comment by ChristopherzwTan** [comment]
Issue #21 is related to this or at least an extension of this.

**Comment by ChristopherzwTan** [comment]
I'll close this issue when we're all happy with the exception catching.

**Comment by ChristopherzwTan** [comment]
here was our error: 
full text: [{u'source_team': u'T0Y5U2B7C', u'text': u'lunchbot list restaurants', u'ts': u'1519428322.000217', u'user': u'U1E2PJSTD', u'team': u'T0Y5U2B7C', u'type': u'message', u'channel': u'G14A1GV4Y'}]
Posting ephemeral message
Traceback (most recent call last):
  File "lunchbot.py", line 258, in <module>
    BOT.run()
  File "lunchbot.py", line 247, in run
    self.handle_lunchbot_command(read_message[0]['text'], read_message[0]['user'])
  File "lunchbot.py", line 207, in handle_lunchbot_command
    self.SLACK_CLIENT.api_call('chat.postEphemeral', user=user, channel=self.CHANNEL, text=msg, as_user=True)
  File "/usr/local/lib/python2.7/dist-packages/slackclient/_client.py", line 80, in api_call
    result = json.loads(self.server.api_call(method, timeout=timeout, **kwargs))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by n-martin** [comment]
I have not been able to reproduce this error. I'm not sure what happened here...

**Comment by ChristopherzwTan** [comment]
Yeah error looks pretty cryptic, didn't seem to find JSON is strange. It can't be from the spam of instructions can it? Strange, let's see what happens tomorrow.

**Comment by n-martin** [comment]
I don't think so... I tried spamming my test Slack server with adds and lists but couldn't make it crash.
